### 

@BASE_URL = http://localhost:5148

# @name debuglogin

POST {{BASE_URL}}/api/auth/debug HTTP/1.1
Content-Type: application/json

{
  "id": 1
}


### Create an order

POST {{BASE_URL}}/api/order HTTP/1.1
Content-Type: application/json

{
  "comment": "Can you deliver it on a golden plate?",
  "items": [
    {
      "choices": [
        23
      ],
      "productId": 5,
      "quantity": 5
    }
  ],
  "pickupTime": null,
  "tableNumber": 1
}


### Create empty order

POST {{BASE_URL}}/api/order HTTP/1.1
Content-Type: application/json

{
  "items": [],
  "pickupTime": null,
  "tableNumber": 1
}


### Get orders

GET {{BASE_URL}}/api/order?count=100&showPaymentPending=true HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}


### Get order

# @prompt id

GET {{BASE_URL}}/api/order/{{id}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}


### Get order statuses

# @prompt id

GET {{BASE_URL}}/api/order/{{id}}/status HTTP/1.1


### Update order status

# @prompt id
# @prompt orderItemId

PUT {{BASE_URL}}/api/order/{{id}}/status/{{orderItemId}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json

{
  "status": "Ready"
}
