### 

@BASE_URL = http://localhost:5148

# @name debuglogin

POST {{BASE_URL}}/api/auth/debug HTTP/1.1
Content-Type: application/json

{
  "id": 1
}


### Get all Products

GET {{BASE_URL}}/api/product HTTP/1.1


### Get product

# @prompt id

GET {{BASE_URL}}/api/product/{{id}} HTTP/1.1


### Create a product

# Returns the id of the newly created product as the response

POST {{BASE_URL}}/api/product HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json

{
  "btw": 20,
  "categoryId": null,
  "description": {
    "Dutch": "Het beste eten",
    "English": "The best food"
  },
  "imgURL": "https://rij62.be/assets/products/bestfood.png",
  "isAvailable": true,
  "menuPresetId": 1,
  "price": 1,
  "stock": 1,
  "title": {
    "Dutch": "Eten",
    "English": "Food"
  }
}


### Update a product

# @prompt id

PUT {{BASE_URL}}/api/product/{{id}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json

{
  "btw": 21,
  "categoryId": 3,
  "description": {
    "Dutch": "",
    "English": ""
  },
  "enabledByPreset": true,
  "id": 23,
  "imgURL": "http://localhost:5148/api/image/35fe8882-d8cb-4a0e-a896-a2b06b63d1b8",
  "isAvailable": false,
  "menuPresetId": null,
  "price": 0,
  "steps": [],
  "stock": 100,
  "title": {
    "Dutch": "Ketchup",
    "English": "Ketchup"
  }
}


### Add a product step

# Returns the id of the create step

# @prompt id

POST {{BASE_URL}}/api/product/{{id}}/step HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json

{
  "Options": [
    7,
    6
  ],
  "defaultOptionId": 8,
  "multipleChoice": false,
  "title": {
    "Dutch": "Kies een soort melk",
    "English": "Choose a type of milk"
  }
}


### Update a product step

# @prompt product_id
# @prompt step_id

PUT {{BASE_URL}}/api/product/{{product_id}}/step/{{step_id}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json

{
  "Options": [
    8,
    9
  ],
  "defaultOptionId": null,
  "multipleChoice": false,
  "title": {
    "Dutch": "Kies een soort melk",
    "English": "Choose a type of milk"
  }
}


### Delete a product step

# @prompt product_id
# @prompt step_id

DELETE {{BASE_URL}}/api/product/{{product_id}}/step/{{step_id}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
Content-Type: application/json


### Delete a product

# @prompt id

DELETE {{BASE_URL}}/api/product/{{id}} HTTP/1.1
Authorization: Bearer {{debuglogin.response.body.$.token}}
